name: Test Action

on:
  push:
    branches:
      - main  # or master, depending on your repo
      # test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f2001734@ds.study.iitm.ac.in
        run: echo "Hello, world!"
